repos:
  - hooks:
      - entry: bash -c "flutter format ."
        id: format_flutter
        language: system
        name: Run flutter format
      - entry: bash -c "flutter analyze ."
        id: analyze_flutter
        language: system
        name: Run flutter analyze
      - entry: bash -c "svgo --pretty -r -f ./"
        id: format_svg
        language: system
        name: Run format svg
      - entry: bash -c "cd domain; flutter pub upgrade; cd ..; cd data; flutter pub
          upgrade; cd ..; cd application; flutter pub upgrade; cd ..; flutter pub
          upgrade"
        id: flutter_pub_upgrade
        language: system
        name: Run flutter pub upgrade
      - entry: bash -c "cd terraform; terraform fmt"
        id: terraform_format
        language: system
        name: Run terraform format
      - entry: 'bash -c "shfmt -w **/*.sh; shellcheck -e SC1090,SC1091,SC2154 **/*.sh"'
        id: shellscript_check
        language: system
        name: Run shellscript check
      - entry: bash -c "yapf --in-place --recursive **/*.py"
        id: python_check
        language: system
        name: Run python check
      - entry: bash -c "ktlint --format"
        id: kotlin_check
        language: system
        name: Run kotlin check
      - entry: bash -c "python3 -m yamllint ."
        id: yaml_check
        language: system
        name: Run yaml check
      - entry: 'bash -c ''find . -name "*.yaml" -exec python3 -m pyaml -r {} \;'''
        id: yaml_format
        language: system
        name: Run yaml format
    repo: local
  - hooks:
      - args:
          - --baseline
          - .secrets.baseline
        id: detect-secrets
    repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
