analyzer:
  errors:
    include_file_not_found: error
    included_file_warning: ignore
    missing_required_param: error
    omit_local_variable_types: error
    unused_element: error
    unused_field: error
    unused_local_variable: error
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - lib/generated_plugin_registrant.dart
    - data/lib/src/firebase_web_config.dart
  plugins:
    - dart_code_metrics
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 80
  metrics-exclude:
    - test/**
  rules:
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic
    - avoid-global-state
    - avoid-late-keyword
    - avoid-missing-enum-constant-in-map
    - avoid-non-ascii-symbols
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - ban-name
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - member-ordering-extended:
        alphabetize: false
        order:
          - constructors
          - public-fields
          - private-fields
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        min-identifier-length: 2
    - prefer-correct-type-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name
    - prefer-trailing-comma
    - tag-name
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-single-widget-per-file
    - prefer-intl-name
    - provide-correct-intl-args
    - avoid-preserve-whitespace-false
    - component-annotation-arguments-ordering
    - prefer-on-push-cd-strategy
include: all_lint_rules.yaml
linter:
  rules:
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    diagnostic_describe_all_properties: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    public_member_api_docs: false
    unnecessary_final: false
