dependencies:
  animations: any
  application:
    path: ./application
  cached_network_image: any
  data:
    path: ./data
  device_info_plus: any
  domain:
    path: ./domain
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_local_notifications: any
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: any
  flutter_svg: any
  go_router: any
  hooks_riverpod: any
  image_picker: any
  in_app_review: any
  intl: any
  logging: any
  mailto: any
  package_info_plus: any
  permission_handler: any
  readmore: any
  syncfusion_flutter_charts: any
  timeago: any
  url_launcher: any
dev_dependencies:
  build_runner: any
  dart_code_metrics: any
  dependency_validator: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  go_router_builder: any
environment:
  sdk: '>=2.17.6 <3.0.0'
flutter:
  assets:
    - assets/images/
  generate: true
  uses-material-design: true
flutter_icons:
  adaptive_icon_background: assets/blank.png
  adaptive_icon_foreground: assets/blank.png
  android: true
  image_path_android: assets/blank.png
  image_path_ios: assets/blank.png
  ios: true
flutter_native_splash:
  color: "#000000"
  fullscreen: true
  image: assets/blank.png
  web: false
name: stock
