# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :distributeDev do
    commit = last_git_commit
    config = JSON.parse(File.read('../app/src/dev/google-services.json'))
    app_id = config['client'][0]['client_info']['mobilesdk_app_id']
    firebase_app_distribution(
      service_credentials_file: "../terraform/sa-dev.json",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      app: app_id,
      groups: "me",
      release_notes: commit[:message]
    )
  end
end
