name: Build
'on':
  push:
    branches:
      - main
env:
  flutter_version: 2.10.5
jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: '${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}'
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ env.flutter_version }}'
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Get dependencies
        run: |
          flutter pub get
          cd data; flutter pub get; cd ..
          cd application; flutter pub get; cd ..
          cd domain; flutter pub get; cd ..
      - name: Format source code
        run: flutter format --set-exit-if-changed .
      - name: Analyze source code
        run: flutter analyze .
      - name: Add config files
        env:
          KEYSTORE_PROPERTIES: '${{ secrets.KEYSTORE_PROPERTIES }}'
          GOOGLE_SERVICES_STAGE_JSON: '${{ secrets.GOOGLE_SERVICES_STAGE_JSON }}'
          RELEASE_JKS: '${{ secrets.RELEASE_JKS }}'
          SERVICE_ACCOUNT_STAGE_JSON: '${{ secrets.SERVICE_ACCOUNT_STAGE_JSON }}'
          ENV_FIREBASE_APP_REGION: '${{ secrets.ENV_FIREBASE_APP_REGION }}'
          ENV_FACEBOOK_APP_ID: '${{ secrets.ENV_FACEBOOK_APP_ID }}'
          ENV_FACEBOOK_APP_SECRET: '${{ secrets.ENV_FACEBOOK_APP_SECRET }}'
        run: >
          sudo echo "$KEYSTORE_PROPERTIES" > android/key.properties

          mkdir -p android/app/src/stage

          sudo echo $GOOGLE_SERVICES_STAGE_JSON >
          android/app/src/stage/google-services.json

          sudo echo $SERVICE_ACCOUNT_STAGE_JSON > terraform/sa-stage.json

          sudo echo "$RELEASE_JKS" | base64 -d > android/release.jks
      - name: Build stage application
        run: >-
          flutter build apk --obfuscate
          --split-debug-info=build/app/outputs/symbols
          --dart-define=ENV_FIREBASE_APP_REGION="$ENV_FIREBASE_APP_REGION"
          --dart-define=ENV_FACEBOOK_APP_ID="$ENV_FACEBOOK_APP_ID"
          --dart-define=ENV_FACEBOOK_APP_SECRET="$ENV_FACEBOOK_APP_SECRET"
          --dart-define=ENV_FLAVOR="stage"
      - name: Distribute stage via Firebase
        run: >-
          cd android; fastlane distributeStage
